### ISSUE TITLE
dark mode button

### ISSUE THREAD

**Issue by sitgdsc2022** [gdscSIT/gdscsit2022#2]
create a dark mode button for all pages.
it will be a plus if it automatically shifts according to day or night.

**Comment by Nincompup** [comment]
hey @sitgdsc2022  may I work on this isssue?

**Comment by sitgdsc2022** [comment]
@Nincompup yes you can proceed with the issue.

**Comment by Nincompup** [comment]
@sitgdsc2022  so please assign this issue to me.
